version: '3'
services:
  happy_shop_web:
    build: .
    image: "happy_shop_react"
    command: "yarn start"
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - "3000:3000"

